# Generated by Django 6.0 on 2025-12-10 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('vin', models.CharField(max_length=17, unique=True, verbose_name='Chassi (VIN)')),
                ('mileage', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('color', models.CharField(max_length=30, verbose_name='Cor')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('sold', 'Vendido'), ('maintenance', 'Em Manutenção')], default='available', max_length=20, verbose_name='Status')),
                ('image_url', models.URLField(blank=True, help_text='Link para a imagem do veículo', verbose_name='URL da Imagem')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('status', models.CharField(choices=[('lead', 'Lead (Potencial)'), ('contacted', 'Contatado'), ('interested', 'Interessado'), ('purchased', 'Comprou'), ('lost', 'Perdido')], default='lead', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Atribuído a')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('sale_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='sales.customer', verbose_name='Cliente')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='sales.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
