# Generated by Django 6.0 on 2025-12-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Imagem do Veículo'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.TextField(blank=True, help_text='Link para a imagem ou código Base64', verbose_name='URL ou Base64 da Imagem'),
        ),
    ]
