# Generated by Django 6.0 on 2026-01-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_vehicle_image_alter_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True, verbose_name='Placa'),
        ),
    ]
