# Generated by Django 6.0 on 2026-01-05 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_vehicle_license_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('pix', 'PIX'), ('ted', 'TED'), ('cash', 'Espécie'), ('cdc', 'Financiamento (CDC)'), ('leasing', 'Financiamento (Leasing)'), ('consortium', 'Consórcio'), ('credit_card', 'Cartão de Crédito'), ('internal', 'Financiamento Próprio (Carne/Boleto)')], max_length=20, verbose_name='Forma de Pagamento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('bank', models.CharField(blank=True, help_text='Para financiamentos e consórcios', max_length=50, verbose_name='Banco/Instituição')),
                ('installments', models.PositiveIntegerField(default=1, help_text='Qtd. parcelas (Crédito/Financ.)', verbose_name='Parcelas')),
                ('quota', models.CharField(blank=True, help_text='Para Consórcios', max_length=50, verbose_name='Cota/Grupo')),
                ('administrator', models.CharField(blank=True, help_text='Para Consórcios', max_length=50, verbose_name='Administradora')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
