# Generated by Django 6.0 on 2026-01-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_down_payment',
            field=models.BooleanField(default=False, help_text='Marque se este pagamento for a entrada/sinal', verbose_name='É Entrada?'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installments',
            field=models.PositiveIntegerField(default=1, help_text='Qtd. parcelas', verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('pix', 'PIX'), ('ted', 'TED'), ('cash', 'Espécie'), ('credit_card', 'Cartão de Crédito'), ('financing_bank', 'Financiamento (CDC - Banco)'), ('financing_brand', 'Financiamento (Montadora)'), ('consortium', 'Consórcio'), ('store_split', 'Parcelamento Direto (Loja)')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
