# Generated by Django 6.0 on 2026-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_is_down_payment_alter_payment_installments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Débito à Vista'), ('credit_spot', 'Crédito à Vista'), ('credit_installment', 'Crédito Parcelado'), ('pix', 'PIX (Agendado/Parcelado)')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
