# Generated by Django 6.0 on 2026-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('debit', 'Débito'), ('credit_spot', 'Crédito'), ('credit_installment', 'Crédito Parcelado'), ('pix', 'PIX')], max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
